### ISSUE TITLE
Error being thrown in dev console 

### ISSUE THREAD

**Issue by tbonfim** [HeyCenturies/acdchrome#1]
I'm facing an issue after installing and not seeing anything changed in AC/DC. I checked extension console and it shows an error, see below: 

![image](https://user-images.githubusercontent.com/2933223/73990945-8a28a000-48ff-11ea-9a28-83d8b3f4012c.png)

Chrome version: Version 72.0.3626.119 (Official Build) (64-bit)

**Comment by HeyCenturies** [comment]
Hey @tbonfim , we are aware of this Synchronous HttpRequest deprecation and we are working on substituting the existing request method, althought that warning should not affect any existing functionalities. When you open ACDC, if you check your browser console (F12) , you'll see a log message like:

"Data Saved [...]  Country: "+ Your country", whats the country being logged?

**Comment by tbonfim** [comment]
Hi @HeyCenturies , i dont see anything print in the console, actually (see screenshot):
![image](https://user-images.githubusercontent.com/2933223/74058072-15567400-499a-11ea-8491-c65bf2786277.png)

Also, in chrome extensions panel, an error is triggered when I load AC/DC:
![image](https://user-images.githubusercontent.com/2933223/74058121-33bc6f80-499a-11ea-9808-e908374b81a4.png)

When I click to see the errors, this is the stack trace shown: 
![image](https://user-images.githubusercontent.com/2933223/74058170-4b93f380-499a-11ea-8d55-5f751739838f.png)

**Comment by HeyCenturies** [comment]
Thanks @tbonfim , the error you're seeing in chrome extension panel is actually a WARN and it is not related to the issue you are facing, the issue might be related to your chrome version, just added a few more log messages and replaced the jquery syntax in one of the functions. Could you please pull the changes and try again?

**Comment by tbonfim** [comment]
Just tried now, with Crome version updated (80.) and still cant see it working. 

I can see the updated logs message
![image](https://user-images.githubusercontent.com/2933223/74070434-ea7a1900-49b5-11ea-98a1-919e646906d5.png)


![image](https://user-images.githubusercontent.com/2933223/74070571-3fb62a80-49b6-11ea-8321-44af453587fb.png)

**Comment by HeyCenturies** [comment]
Okay, the issue was that the feature for adding the button was not mapping the plus (+) button:
![image](https://user-images.githubusercontent.com/28064555/74071312-60947500-49e2-11ea-9d6e-f2dcce7002c8.png)
It works when clicking anywhere but the button, we'll fix that on the next update. Thanks for reporting @tbonfim !

**Comment by tbonfim** [comment]
Thanks @HeyCenturies !
